# Generated by Django 6.0.2 on 2026-02-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.category'),
        ),
        migrations.AddField(
            model_name='genre',
            name='category_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.category'),
        ),
        migrations.AddField(
            model_name='genre',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.category'),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_en',
            field=models.ManyToManyField(null=True, to='movie_app.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_ky',
            field=models.ManyToManyField(null=True, to='movie_app.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_ru',
            field=models.ManyToManyField(null=True, to='movie_app.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_en',
            field=models.ManyToManyField(null=True, to='movie_app.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_ky',
            field=models.ManyToManyField(null=True, to='movie_app.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_ru',
            field=models.ManyToManyField(null=True, to='movie_app.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_en',
            field=models.ManyToManyField(null=True, to='movie_app.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_ky',
            field=models.ManyToManyField(null=True, to='movie_app.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_ru',
            field=models.ManyToManyField(null=True, to='movie_app.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_en',
            field=models.ManyToManyField(null=True, to='movie_app.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_ky',
            field=models.ManyToManyField(null=True, to='movie_app.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_ru',
            field=models.ManyToManyField(null=True, to='movie_app.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielanguage',
            name='language_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielanguage',
            name='language_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielanguage',
            name='language_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
