# Generated by Django 6.0.2 on 2026-02-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_actor_actor_name_en_actor_actor_name_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_name_ky',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='bio_ky',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ky',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_name_ky',
        ),
        migrations.RemoveField(
            model_name='director',
            name='bio_ky',
        ),
        migrations.RemoveField(
            model_name='director',
            name='director_name_ky',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='category_ky',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_name_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actor_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_name_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slogan_ky',
        ),
        migrations.RemoveField(
            model_name='movielanguage',
            name='language_ky',
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=models.PositiveSmallIntegerField(choices=[(144, 144), (360, 360), (480, 480), (720, 720), (1080, 1080)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.review'),
        ),
    ]
