# Generated by Django 6.0.2 on 2026-02-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_remove_actor_actor_name_ky_remove_actor_bio_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='category_ru',
        ),
    ]
