# Generated by Django 6.0.2 on 2026-02-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_genre_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies_list', to='movie_app.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_en',
            field=models.ManyToManyField(null=True, related_name='movies_list', to='movie_app.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_ru',
            field=models.ManyToManyField(null=True, related_name='movies_list', to='movie_app.genre'),
        ),
    ]
