# Generated by Django 6.0.2 on 2026-02-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_moments_movie_alter_movielanguage_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='movies_country', to='movie_app.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_en',
            field=models.ManyToManyField(null=True, related_name='movies_country', to='movie_app.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_ru',
            field=models.ManyToManyField(null=True, related_name='movies_country', to='movie_app.country'),
        ),
    ]
